### PR TITLE
Update libraries to imgui-rs 10.0

### PR DESCRIPTION
**Pull request by Diegovsky**
Did some quick changes so the libs build with version 10 of imgui-rs. Did not really focus on the example as of yet. What do you think?

### CODE REVIEW

**Comment by benmkw** [comment]
Thanks for your work, if the examples compile again I will gladly merge this. 

I'm currently mostly using egui instead of imgui so I'm not actively using it and I did not follow the most recent imgui-rs changes yet so if you can adapt the example to the new API that would be great.

**Comment by benmkw** [comment]
I just went ahead and updates cimnodes and also updated the example to imgui 0.10. If there are remaining issues feel free to update this PR or open a new one. You might also be interested in https://github.com/benmkw/imnodes-rs/issues/5#issuecomment-1501066501

**Comment by Diegovsky** [comment]
> I'm currently mostly using egui instead of imgui so I'm not actively using it and I did not follow the most recent imgui-rs changes yet so if you can adapt the example to the new API that would be great.

Well, I'm using this for a project at uni, and have been wanting to push this to crates.io. Would you feel comfortable giving me maintainer status and publishing it?

**Comment by benmkw** [comment]
Did you try using git dependencies as described here https://github.com/benmkw/imnodes-rs/issues/3#issuecomment-1225884731 / does that solution work for you?

Otherwise I should probably look into uploading it as it appears there is at least a reoccurring interest in it.

**Comment by Diegovsky** [comment]
It does work, however I would love to publish it so more people can use it. I'm willing to maintain it btw.

**Comment by benmkw** [comment]
just published it 

https://crates.io/crates/imnodes-sys
and
https://crates.io/crates/imnodes

**Comment by Diegovsky** [comment]
cool thanks :)

**Pull request closed without merging**
